name: audio_cast
description: A starting point for Dart libraries or applications.
# version: 1.0.0
homepage: https://www.peterscode.dev

environment:
  sdk: '>=2.10.0 <2.12.0'

dependencies:
  state_notifier: ^0.6.0

  #DLNA
  http: ^0.12.2
  http_server: ^0.9.8+3
  file: ^5.2.1
  mp3_info: ^0.1.4
  #upnp: ^2.0.1
  #upnp:
  #  git: https://github.com/moda20/upnp.dart.git
  upnp:
    git: https://github.com/peterscodee/upnp_dart.git
    #path: C:\Users\David\IdeaProjects\upnp_dart

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
