name: audio_cast
description: A starting point for Dart libraries or applications.
# version: 1.0.0
homepage: https://www.peterscode.dev

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  state_notifier: ^0.6.0

  #DLNA
  http: ^0.12.2
  http_server: ^0.9.8+3
  upnp:
    git: https://github.com/peterscodee/upnp_dart.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
